// !!---------------------------------------------------!!
// !!---------- AUTO-GENERATED: Do not edit! -----------!!
// !!---------------------------------------------------!!

export enum AgeBracket {
  Youth = 1,
  Child = 2,
  Adult = 3,
  Elder = 4,
}

export enum AllowanceType {
  Meals = 1,
  Research = 2,
  Accomodation = 3,
  Travel = 4,
  Laptop = 5,
  TextBooks = 6,
  Tuition = 7,
  Registration = 8,
}

export enum AlternateIdentityType {
  BirthCertificateNumber = 1,
  DriverSLicense = 2,
  EmployeeNumber = 3,
  EtqeRecordNumber = 4,
  HsrcRegisterNumber = 5,
  None = 6,
  PassportNumber = 7,
  RefugeeNumber = 8,
  SaqaMemberID = 9,
  StudentNumber = 10,
  TemporaryIDNumber = 11,
  Unknown = 12,
  WorkPermitNumber = 13,
}

export enum ApplicantType {
  Nominated = 1,
  Individual = 2,
}

export enum ApplicationType {
  BursaryRegistration = 1,
}

export enum ApprovalStatus {
  Pending = 1,
  Approved = 2,
  Rejected = 3,
  Verified = 4,
  Signed = 5,
  Withdrawn = 6,
}

export enum ApprovalType {
  Verification = 1,
  Signature = 2,
  Authorisation = 3,
}

export enum Area {
  Randburg = 1,
}

export enum AuthenticationType {
  Basic = 1,
  Microsoft = 2,
}

export enum CalculationType {
  Cumulative = 1,
  NonCumulative = 2,
}

export enum Checklist {
  UploadFeasibilityStudyReport = 2,
  LevelOfFeasibility = 3,
}

export enum ChecklistOption {
  LevelOfFeasibilityHigh = 1,
  LevelOfFeasibilityMedium = 3,
  LevelOfFeasibilityLOW = 4,
  LevelOfFeasibilityTBD = 6,
}

export enum Citizenship {
  DualSAPlusOther = 1,
  Other = 2,
  PermanentResident = 3,
  SouthAfrica = 4,
  Unknown = 5,
}

export enum City {
  Johannesburg = 1,
  Pretoria = 2,
  CapeTown = 3,
  Bloemfontein = 4,
}

export enum CommunityType {
  Rural = 1,
  Urban = 2,
  Unknown = 3,
}

export enum Country {
  Afghanistan = 1,
  AlandIslands = 2,
  Albania = 3,
  Algeria = 4,
  AmericanSamoa = 5,
  Andorra = 6,
  Angola = 7,
  Anguilla = 8,
  Antarctica = 9,
  AntiguaANDBarbuda = 10,
  Argentina = 11,
  Armenia = 12,
  Aruba = 13,
  Australia = 14,
  Austria = 15,
  Azerbaijan = 16,
  Bahamas = 17,
  Bahrain = 18,
  Bangladesh = 19,
  Barbados = 20,
  Belarus = 21,
  Belgium = 22,
  Belize = 23,
  Benin = 24,
  Bermuda = 25,
  Bhutan = 26,
  BoliviaPlurinationalStateOF = 27,
  BonaireSintEustatiusANDSaba = 28,
  BosniaANDHerzegovina = 29,
  Botswana = 30,
  BouvetIsland = 31,
  Brazil = 32,
  BritishIndianOceanTerritory = 33,
  BruneiDarussalam = 34,
  Bulgaria = 35,
  BurkinaFaso = 36,
  Burundi = 37,
  Cambodia = 38,
  Cameroon = 39,
  Canada = 40,
  CapeVerde = 41,
  CaymanIslands = 42,
  CentralAfricanRepublic = 43,
  Chad = 44,
  Chile = 45,
  China = 46,
  ChristmasIsland = 47,
  CocosKeelingIslands = 48,
  Colombia = 49,
  Comoros = 50,
  Congo = 51,
  CongoTHEDemocraticRepublicOFTHE = 52,
  CookIslands = 53,
  CostaRica = 54,
  CoteDivoire = 55,
  Croatia = 56,
  Cuba = 57,
  Curacao = 58,
  Cyprus = 59,
  CzechRepublic = 60,
  Denmark = 61,
  Djibouti = 62,
  Dominica = 63,
  DominicanRepublic = 64,
  Ecuador = 65,
  Egypt = 66,
  ELSalvador = 67,
  EquatorialGuinea = 68,
  Eritrea = 69,
  Estonia = 70,
  Ethiopia = 71,
  FalklandIslandsMalvinas = 72,
  FaroeIslands = 73,
  Fiji = 74,
  Finland = 75,
  France = 76,
  FrenchGuiana = 77,
  FrenchPolynesia = 78,
  FrenchSouthernTerritories = 79,
  Gabon = 80,
  Gambia = 81,
  Georgia = 82,
  Germany = 83,
  Ghana = 84,
  Gibraltar = 85,
  Greece = 86,
  Greenland = 87,
  Grenada = 88,
  Guadeloupe = 89,
  Guam = 90,
  Guatemala = 91,
  Guernsey = 92,
  Guinea = 93,
  GuineaBissau = 94,
  Guyana = 95,
  Haiti = 96,
  HeardIslandANDMcdonaldIslands = 97,
  HolySEEVaticanCityState = 98,
  Honduras = 99,
  HongKong = 100,
  Hungary = 101,
  Iceland = 102,
  India = 103,
  Indonesia = 104,
  IranIslamicRepublicOF = 105,
  Iraq = 106,
  Ireland = 107,
  IsleOFMAN = 108,
  Israel = 109,
  Italy = 110,
  Jamaica = 111,
  Japan = 112,
  Jersey = 113,
  Jordan = 114,
  Kazakhstan = 115,
  Kenya = 116,
  Kiribati = 117,
  KoreaDemocraticPeoplesRepublicOF = 118,
  KoreaRepublicOF = 119,
  Kuwait = 120,
  Kyrgyzstan = 121,
  LAOPeoplesDemocraticRepublic = 122,
  Latvia = 123,
  Lebanon = 124,
  Lesotho = 125,
  Liberia = 126,
  Libya = 127,
  Liechtenstein = 128,
  Lithuania = 129,
  Luxembourg = 130,
  Macao = 131,
  MacedoniaTHEFormerYugoslavRepublicOF = 132,
  Madagascar = 133,
  Malawi = 134,
  Malaysia = 135,
  Maldives = 136,
  Mali = 137,
  Malta = 138,
  MarshallIslands = 139,
  Martinique = 140,
  Mauritania = 141,
  Mauritius = 142,
  Mayotte = 143,
  Mexico = 144,
  MicronesiaFederatedStatesOF = 145,
  MoldovaRepublicOF = 146,
  Monaco = 147,
  Mongolia = 148,
  Montenegro = 149,
  Montserrat = 150,
  Morocco = 151,
  Mozambique = 152,
  Myanmar = 153,
  Namibia = 154,
  Nauru = 155,
  Nepal = 156,
  Netherlands = 157,
  NEWCaledonia = 158,
  NEWZealand = 159,
  Nicaragua = 160,
  Niger = 161,
  Nigeria = 162,
  Niue = 163,
  NorfolkIsland = 164,
  NorthernMarianaIslands = 165,
  Norway = 166,
  Oman = 167,
  Pakistan = 168,
  Palau = 169,
  PalestinianTerritoryOccupied = 170,
  Panama = 171,
  PapuaNEWGuinea = 172,
  Paraguay = 173,
  Peru = 174,
  Philippines = 175,
  Pitcairn = 176,
  Poland = 177,
  Portugal = 178,
  PuertoRico = 179,
  Qatar = 180,
  Reunion = 181,
  Romania = 182,
  RussianFederation = 183,
  Rwanda = 184,
  SaintBarthelemy = 185,
  SaintHelenaAscensionANDTristanDACunha = 186,
  SaintKittsANDNevis = 187,
  SaintLucia = 188,
  SaintMartinFrenchPart = 189,
  SaintPierreANDMiquelon = 190,
  SaintVincentANDTHEGrenadines = 191,
  Samoa = 192,
  SANMarino = 193,
  SAOTomeANDPrincipe = 194,
  SaudiArabia = 195,
  Senegal = 196,
  Serbia = 197,
  Seychelles = 198,
  SierraLeone = 199,
  Singapore = 200,
  SintMaartenDutchPart = 201,
  Slovakia = 202,
  Slovenia = 203,
  SolomonIslands = 204,
  Somalia = 205,
  SouthAfrica = 206,
  SouthGeorgiaANDTHESouthSandwichIslands = 207,
  SouthSudan = 208,
  Spain = 209,
  SRILanka = 210,
  Sudan = 211,
  Suriname = 212,
  SvalbardANDJANMayen = 213,
  Swaziland = 214,
  Sweden = 215,
  Switzerland = 216,
  SyrianArabRepublic = 217,
  TaiwanProvinceOFChina = 218,
  Tajikistan = 219,
  TanzaniaUnitedRepublicOF = 220,
  Thailand = 221,
  TimorLeste = 222,
  Togo = 223,
  Tokelau = 224,
  Tonga = 225,
  TrinidadANDTobago = 226,
  Tunisia = 227,
  Turkey = 228,
  Turkmenistan = 229,
  TurksANDCaicosIslands = 230,
  Tuvalu = 231,
  Uganda = 232,
  Ukraine = 233,
  UnitedArabEmirates = 234,
  UnitedKingdom = 235,
  UnitedStates = 236,
  UnitedStatesMinorOutlyingIslands = 237,
  Uruguay = 238,
  Uzbekistan = 239,
  Vanuatu = 240,
  VenezuelaBolivarianRepublicOF = 241,
  VietNAM = 242,
  VirginIslandsBritish = 243,
  VirginIslandsUS = 244,
  WallisANDFutuna = 245,
  WesternSahara = 246,
  Yemen = 247,
  Zambia = 248,
  Zimbabwe = 249,
}

export enum DemographicType {
  AfricanWomenYouthRuralAbled = 1,
  AfricanWomen = 2,
  Women = 3,
  Youth = 4,
  PeopleWithDisabilityDisabledRememberingDifficulty = 5,
  PeopleWithDisabilityDisabledSeeingDifficulty = 6,
  PeopleWithDisablityDisabledSelfcareDifficulty = 7,
  PeopleWithDisablityDisabledWalkingDifficulty = 8,
  Rural = 9,
}

export enum DepartmentType {
  Bursaries = 1,
  ECD = 2,
  SP = 3,
  SPI = 4,
  Pmvr = 5,
}

export enum DepartmentTypePersonType {
  BursariesFinancialAidOfficer = 1,
  BursariesSigningOfficer = 2,
  BursariesBillingOfficer = 3,
  BursariesAccessOfficer = 4,
}

export enum DepartmentTypeRole {
  PmvrPmvrManager = 1,
  PmvrPmvrPlanner = 2,
  BursariesBursaryManager = 3,
  BursariesBursaryEvaluator = 4,
  BursariesBursaryApprover = 5,
  PmvrSetmisReports = 14,
  PmvrSsetaAdmin = 18,
  PmvrManagementReports = 35,
  PmvrFinancialReports = 36,
  BursariesAccessOfficer = 37,
}

export enum Designation {
  Assessor = 1,
  Moderator = 2,
}

export enum DesignationStructureStatus {
  Deregistered = 1,
  Proposed = 2,
  Registered = 3,
  Reregistered = 4,
  Unsuccessful = 5,
  Withdrawn = 6,
}

export enum Disability {
  RememberingDifficulty = 1,
  SeeingDifficulty = 2,
  SelfCareDifficulty = 3,
  WalkingDifficulty = 4,
  None = 5,
}

export enum DisabilityRating {
  NoDifficulty = 1,
  SomeDifficulty = 2,
  ALotOfDifficulty = 3,
  CannotDoAtAll = 4,
  DoNotKnow = 5,
  CannotYetBeDetermined = 6,
}

export enum DisbursementType {
  Learnership = 1,
  Allowance = 2,
  Registration = 3,
}

export enum DocumentType {
  CertifiedIdentityDocument = 1,
  LearnerList = 2,
  ProofOfResidence = 3,
  BursaryContract = 4,
  FeasibilityStudyReport = 5,
  ProofOfEmployment = 6,
  AnnualPerformancePlan = 7,
  SectorSkillsPlan = 8,
  StrategicPlan = 9,
  AOPPlan = 10,
  Template = 11,
  InstitutionContract = 12,
  InstitutionContractEvidence = 13,
  Invoice = 14,
  BursaryContractEvidence = 15,
  BursaryApplicantAppeal = 16,
  UnemploymentAffidavit = 17,
  ProofOfRegistrationFeeStatement = 18,
}

export enum Dossier {
  EmployedBursaryApplicant = 1,
  PersonIdentityDocument = 4,
  PerformancePlanEvidence = 5,
  UnemployedBursaryApplicant = 8,
}

export enum DossierDocumentType {
  IdentityDocument_1 = 1,
  ProofOfEmployment = 2,
  AnnualPerformancePlan = 10,
  SectorSkillsPlan = 11,
  StrategicPlan = 14,
  AnnualOperationPlan = 15,
  IdentityDocument_17 = 17,
  ProofOfRegistrationFeeStatement_22 = 22,
  UnemploymentAffidavit = 23,
  ProofOfRegistrationFeeStatement_24 = 24,
}

export enum EconomicType {
  Employed = 1,
  Unemployed = 2,
  EmployedOnlyForThePurposeOfTheQualification = 3,
  Unknown = 4,
}

export enum EconomicTypeInterventionType {
  BursariesForEmployed = 1,
  BursariesForUnemployed = 2,
}

export enum EducationTrainingQualityEntity {
  Theta = 1,
  Teta = 2,
  Services = 3,
  Mappp = 4,
  Fpmseta = 5,
  SASSeta = 6,
  Merseta = 7,
  Micts = 8,
  Ceta = 9,
  Sapftc = 10,
  Fasset = 11,
  AgriSeta = 12,
  CHE = 13,
  WRseta = 14,
  Cathsseta = 15,
  LGSeta = 16,
  Foodbev = 17,
  EtdpSeta = 18,
  Inseta = 19,
  HWSeta = 20,
  Ewseta = 21,
  MQA = 22,
  Umalusi = 23,
  Saica = 24,
  Sanc = 25,
  Bankseta = 26,
  Sapc = 27,
  PAB = 28,
  Sabpp = 29,
  AEE = 30,
  Pseta = 31,
  Chieta = 32,
  Isett = 33,
  CtflSeta = 34,
  Fieta = 35,
  Saahsp = 36,
  Qcto = 37,
  Hpcsa = 38,
  KRG = 39,
  Dgtr = 40,
}

export enum EmployerApprovalStatus {
  Active = 1,
  Inactive = 2,
  Legacy = 3,
}

export enum EnrolmentStatus {
  Achieved = 1,
  Certificated = 2,
  CompletedToBeAssessed = 3,
  Discontinued = 4,
  Enrolled = 5,
  NonEndorsedAchievement = 6,
  WaitingForWIL = 7,
  WILInProgress = 8,
}

export enum EnrolmentStatusReason {
  ChangedPriorities = 1,
  Deceased = 2,
  Dismissal = 3,
  Employment = 4,
  ExamEnrolmentRejected = 5,
  ExchangeStudent = 6,
  FinancialReasons = 7,
  MedicalReasons = 8,
  NoneGiven = 9,
  Other = 10,
  SocialReasons = 11,
  StudyPermitNotApproved = 12,
  Suspension = 13,
}

export enum EnrolmentType {
  DistanceLearning = 1,
  DistanceLearningAtMoreThanOneProvider = 2,
  MixedMode = 3,
  Other = 4,
  ResidentialContactAtMoreThanOneProvider = 5,
  ResidentialContactLearning = 6,
  SelfStudy = 7,
  WorkPlaceLearning = 8,
}

export enum EquipmentCategory {
  Salon = 1,
  BeautyTherapy = 2,
  NailTechnology = 3,
}

export enum EquipmentCategoryGroup {
  BeautyPersonalServices = 1,
  HospitalityTourism = 2,
  EngineeringTechnical = 3,
  InformationTechnology = 4,
  ConstructionBuilding = 5,
  BusinessCommerce = 6,
  CreativeDesign = 7,
  AgricultureEnvironment = 8,
  HealthSafety = 9,
  SocialServices = 10,
  SecurityProtection = 11,
  MiningExtraction = 12,
  GeneralFacilities = 13,
}

export enum EquityCode {
  African = 1,
  Coloured = 2,
  Indian = 3,
  Unknown = 4,
  White = 5,
}

export enum ETQE {
  Theta = 1,
  Teta = 2,
  Services = 3,
  Mappp = 4,
  Fpmseta = 5,
  SASSeta = 6,
  Merseta = 7,
  Micts = 8,
  Ceta = 9,
  Sapftc = 10,
  Fasset = 11,
  AgriSeta = 12,
  CHE = 13,
  WRseta = 14,
  Cathsseta = 15,
  LGSeta = 16,
  Foodbev = 17,
  EtdpSeta = 18,
  Inseta = 19,
  HWSeta = 20,
  Ewseta = 21,
  MQA = 22,
  Umalusi = 23,
  Saica = 24,
  Sanc = 25,
  Bankseta = 26,
  Sapc = 27,
  PAB = 28,
  Sabpp = 29,
  AEE = 30,
  Pseta = 31,
  Chieta = 32,
  Isett = 33,
  CtflSeta = 34,
  Fieta = 35,
  Saahsp = 36,
  Qcto = 37,
  Hpcsa = 38,
  KRG = 39,
  Dgtr = 40,
}

export enum EvaluationCriteria {
  Motivation = 3,
  Availability = 4,
  Capacity = 5,
}

export enum EvaluationScore {
  SupportMotivationIsClearlyArticulatedAndComprehensive = 1,
  SupportMotivationIsArticulatedAndIsAverageOrLessThanAcceptable = 2,
  SupportMotivationIsWeakAndHasGapsOrInadequateInformation = 3,
  ClearAndComprehensiveDetailsOfTheFacilityAvailability = 4,
  DetailsOfTheFacilityAvailabilityOfferedAreConsideredAdequateOrLessThanAcceptable = 5,
  DetailsOfTheFacilityAvailabilityAreWeakOrInadequate = 6,
  CapacityOfManagementOfTheProjectAndIsArticulatedAndComprehensive = 7,
  CapacityOfManagementOfTheProjectIsConsideredAverageOrLessThanAcceptable = 8,
  CapacityOfManagementOfTheProjectIsConsideredWeakOrInadequate = 9,
}

export enum EvaluationTemplate {
  SalonEquipmentEvaluation = 1,
}

export enum EvaluationTemplateCriteria {
  SalonEquipmentEvaluationMotivation = 1,
  SalonEquipmentEvaluationAvailability = 3,
  SalonEquipmentEvaluationCapacity = 5,
}

export enum EventFormat {
  Physical = 1,
  Virtual = 2,
}

export enum EventSource {
  ECDStaff = 1,
  ECDPartner = 2,
}

export enum EventType {
  Capacitation = 3,
  ELearning = 5,
}

export enum EvidenceType {
  Application = 1,
  Document = 2,
  Event = 3,
}

export enum FeasibilityType {
  Achievable = 1,
  NotAchievable = 2,
}

export enum FieldOfStudy {
  HumanResource = 1,
  Marketing = 2,
  EntrepreneurshipAndSmmeDevelopment = 3,
  MediaAndCommunications = 4,
  ProjectManagement = 5,
  WasteManagementAndCleaning = 6,
  DermatologyAndRelatedFields = 7,
  CosmeticDevelopment = 8,
  RealEstateAndPropertyDevelopment = 9,
  BusinessManagementAdministration = 10,
  Economics = 11,
  SocialSciences = 12,
  Metallurgy = 13,
  Mechatronics = 14,
  ActuarialScience = 15,
  MedicalScience = 16,
  TelecommunicationEngineering = 17,
  Sociology = 18,
  Anthropology = 19,
  WebAndMultimediaDevelopment = 20,
}

export enum FundingType {
  EmployerFunded = 1,
  LearnerFunded = 2,
  NA = 3,
  Other = 4,
  SetaFunded = 5,
}

export enum Gender {
  Female = 1,
  Male = 2,
}

export enum GlobalConfiguration {
  CurrentVatRate = 1,
}

export enum IdentityType {
  IdentityCard = 1,
  IdentityBook = 2,
  DrivingLicense = 3,
}

export enum ImpactType {
  Validity = 1,
  ScopeLimitation = 2,
  Accuracy = 3,
}

export enum InputType {
  Document = 2,
  Text = 3,
  Date = 4,
  Numeric = 5,
  Currency = 9,
  Checkbox = 10,
  Dropdown = 11,
  Radio = 12,
}

export enum InternshipStatus {
  Active = 1,
  Completed = 2,
  Discontinued = 3,
}

export enum InterventionType {
  BursariesForUnemployed = 1,
  BursariesForEmployed = 2,
  SpecialProjectsForConstruction = 3,
  SpecialProjectsForEquipment = 4,
  ELearningOutreach = 5,
  ELearningSelfService = 6,
  CapacityBuildingWorkshop = 7,
}

export enum Language {
  Afrikaans = 1,
  English = 2,
  IsiNdebele = 3,
  IsiXhosa = 4,
  IsiZulu = 5,
  Other = 6,
  SePedi = 7,
  SeSotho = 8,
  SeTswana = 9,
  SiSwati = 10,
  SouthAfricanSignLanguage = 11,
  TshiVenda = 12,
  Unknown = 13,
  XiTsonga = 14,
}

export enum LearningProgrammeType {
  NA = 1,
  Bursary = 2,
  TvetPlacement = 3,
  UniversityPlacement = 4,
  Candidacy = 5,
  RecognitionOfPriorLearning = 6,
  LecturerDevelopment = 7,
  SkillsProgramme = 8,
  AET = 9,
  ShortProgramme = 10,
  Cadetship = 11,
}

export enum LevelOfStudy {
  Undergraduate = 1,
  Honours = 2,
  Masters = 3,
  PHD = 4,
  TvetColleges = 5,
}

export enum MfaType {
  None = 1,
  Email = 2,
  SMS = 3,
}

export enum MimeType {
  PDF = 1,
  JPG = 2,
  PNG = 3,
  BMP = 4,
  Xlsx = 5,
  XLS = 6,
  DOC = 7,
}

export enum MunicipalityDistrict {
  WestCoastDistrictMunicipality = 1,
  BolandDistrictMunicipality = 2,
  CityOfJohannesburgMetropolitanMunicipality = 3,
}

export enum MunicipalityLocal {
  CityOfJohannesburgMetro = 1,
}

export enum Nationality {
  Angola = 1,
  AsianCountries = 2,
  AustraliaOceaniaCountries = 3,
  Botswana = 4,
  EuropeanCountries = 5,
  Lesotho = 6,
  Malawi = 7,
  Mauritius = 8,
  Mozambique = 9,
  Namibia = 10,
  NorthAmericanCountries = 11,
  OtherRestOfOceania = 12,
  RestOfAfrica = 13,
  SadcExceptSA = 14,
  Seychelles = 15,
  SouthCentralAmericanC = 16,
  SouthAfrica = 17,
  Swaziland = 18,
  Tanzania = 19,
  Unspecified = 20,
  Zaire = 21,
  Zambia = 22,
  Zimbabwe = 23,
}

export enum NonNQFInterventionStatus {
  Active = 1,
  Inactive = 2,
  Provisional = 3,
}

export enum Template {
  BursaryApplicationSuccess = 1,
}

export enum NotificationType {
  Reminder = 1,
  Message = 2,
  Comment = 3,
}

export enum NQFLevel {
  NQFLevel01 = 1,
  NQFLevel02 = 2,
  NQFLevel03 = 3,
  NQFLevel04 = 4,
  NQFLevel05 = 5,
  NQFLevel06 = 6,
  NQFLevel07 = 7,
  NQFLevel08 = 8,
  NQFLevel09 = 9,
  NQFLevel10 = 10,
}

export enum NQFSubFramework {
  Sfna = 1,
  Gfetqsf = 2,
  Sfap = 3,
  Oqsf = 4,
  Heqsf = 5,
}

export enum Object {
  SystemUser = 1,
  SystemUserRole = 2,
  EmailQueue = 3,
  SmsQueue = 4,
  SystemUserType = 5,
  Role = 6,
  RoleObject = 7,
  Permission = 8,
  Object = 9,
  AuthenticationType = 10,
  DocumentType = 12,
  Document = 13,
  MimeType = 14,
  ObjectType = 15,
  MfaType = 16,
  Template = 17,
  TemplateType = 18,
  Event = 19,
  AgeBracket = 20,
  Allowance = 21,
  AllowanceType = 22,
  Application = 23,
  ApplicationType = 25,
  Approval = 26,
  ApprovalStatus = 27,
  ApprovalStep = 28,
  ApprovalType = 29,
  Area = 30,
  Attendee = 31,
  BursaryApplicant = 32,
  BursaryApplicantEducation = 33,
  BursaryApplicantEmployment = 34,
  BursaryApplicantInstitution = 35,
  BursaryApplicantQualification = 36,
  CalculationType = 37,
  Checklist = 38,
  ChecklistInstance = 39,
  ChecklistOption = 40,
  City = 41,
  CommunityType = 42,
  DatabaseAudit = 43,
  DemographicType = 44,
  DepartmentType = 45,
  Disability = 46,
  Disbursement = 47,
  DisbursementType = 49,
  Dossier = 50,
  EquityCode = 53,
  EventFormat = 54,
  EventType = 55,
  EventVenue = 56,
  EvidenceType = 57,
  FieldOfStudy = 59,
  FundingCap = 60,
  Gender = 61,
  IdentityType = 62,
  ImpactType = 63,
  Indicator = 64,
  IndicatorAchievement = 65,
  IndicatorDescriptor = 66,
  IndicatorEmpowerment = 67,
  IndicatorEvidence = 68,
  IndicatorIssue = 69,
  IndicatorResult = 70,
  InputType = 71,
  Intervention = 73,
  InterventionType = 74,
  Language = 75,
  LevelOfStudy = 76,
  MunicipalityDistrict = 77,
  MunicipalityLocal = 78,
  Nationality = 79,
  NQFLevel = 80,
  Organisation = 81,
  OrganisationType = 83,
  PaymentFrequency = 84,
  PerformancePlan = 85,
  Person = 86,
  PersonType = 87,
  Programme = 88,
  Province = 91,
  QualificationLevel = 92,
  ReportingPeriod = 93,
  ReportingType = 94,
  RiskRating = 95,
  SourceSystem = 96,
  Stage = 97,
  StageDependency = 98,
  StageInstance = 99,
  StatsSaArea = 101,
  SubProgramme = 102,
  SupportType = 103,
  Title = 104,
  EquipmentCategory = 106,
  EquipmentCategoryGroup = 107,
  EvaluationCriteria = 108,
  EvaluationScore = 109,
  EvaluationTemplate = 110,
  EvaluationTemplateCriteria = 111,
  DossierDocumentType = 112,
  Evaluation = 113,
  EvaluationResult = 114,
  PriorityFieldOfStudy = 116,
  InterventionIndicator = 117,
  Status = 118,
  StatusObject = 119,
  EconomicType = 120,
  FeasibilityType = 121,
  InterventionOrganisation = 122,
  Notification = 123,
  Template = 124,
  NotificationType = 125,
  OrganisationPerson = 126,
  RecommendationType = 127,
  OrganisationFundingCap = 128,
  InterventionOrganisationLearnerList = 129,
  OrganisationContractDeprecated = 130,
  OrganisationInvoice = 131,
  DocumentSignature = 132,
  BursaryApplicantRejectionReason = 133,
  PersonTypeRole = 134,
  RejectionCategory = 135,
  RejectionReason = 136,
  StatusObjectPermission = 137,
  ApplicantType = 138,
  EconomicTypeInterventionType = 139,
  StatusCascadeRule = 140,
  ProviderClass = 142,
  PersonOrganisationPersonType = 143,
  GlobalConfiguration = 144,
  BursaryApplicantAppeal = 145,
  BursaryApplicantAppealTimeline = 146,
  AlternateIdentityType = 148,
  Citizenship = 149,
  Country = 150,
  Designation = 151,
  DesignationStructureStatus = 152,
  DisabilityRating = 153,
  EmployerApprovalStatus = 154,
  EnrolmentStatus = 155,
  EnrolmentStatusReason = 156,
  EnrolmentType = 157,
  FundingType = 158,
  InternshipStatus = 159,
  NonNQFInterventionStatus = 160,
  NQFSubFramework = 161,
  Occupation = 162,
  PartOf = 163,
  PopiActStatus = 164,
  ProviderType = 165,
  SaqaField = 166,
  SaqaLearningProgramme = 167,
  SaqaQualification = 168,
  SaqaSubField = 169,
  YearOfStudy = 170,
  LearningProgrammeType = 178,
  ProviderStatus = 179,
  SetaType = 180,
  TradeTestResult = 181,
  TradeTestResultReason = 182,
  EducationTrainingQualityEntity = 188,
  Employer = 189,
  InternshipPlacement = 190,
  LearnershipEnrolment = 191,
  NonNQFIntervention = 192,
  NonNQFInterventionEnrolment = 193,
  PersonDesignation = 194,
  Provider = 195,
  QualificationEnrolment = 196,
  Quarter = 197,
  TradeTest = 198,
  UnitStandardEnrolment = 199,
  ElectronicLearningApplicant = 200,
  EventRequest = 201,
  EventSource = 202,
  PortalOrigin = 203,
  SetmisEmployer = 204,
  SetmisInternshipPlacement = 205,
  SetmisLearnershipEnrolment = 206,
  SetmisNonNQFIntervention = 207,
  SetmisNonNQFInterventionEnrolment = 208,
  SetmisPerson = 209,
  SetmisPersonDesignation = 210,
  SetmisProvider = 211,
  SetmisQualificationEnrolment = 212,
  SetmisTradeTest = 213,
  SetmisUnitStandardEnrolment = 214,
  CareerDevelopmentEvents = 215,
  CareerDevelopmentPractitioners = 216,
  CareerDevelopmentWorkshops = 217,
  CBOsNGOsNPOsTradeUnion = 218,
  DevelopmentSupport = 219,
  TrainedOnEntrepreneurship = 220,
  PartnerRoleRequest = 221,
  PartnerRoleRequestOrganisationPerson = 222,
  PartnerRoleRequestPersonOrganisationPersonType = 223,
  StaffRoleRequest = 224,
  CentresOfSpecialisation = 225,
  CompletedWBLAbsorbed = 226,
  DBCodeGenWhitelist = 227,
  DepartmentTypePersonType = 228,
  DepartmentTypeRole = 229,
  DiscretionaryGrant = 230,
  Firms = 231,
  InfrastructureDevelopment = 232,
  LearningProgrammesComplete = 233,
  LearningProgrammesEnrolled = 234,
  LecturersAwardedBursaries = 235,
  LecturerSkillsProgrammes = 236,
  RuralDevelopmentProjects = 237,
  SectorResearch = 238,
  SetaEmployerPartnerships = 239,
  SetaGoodGovernance = 240,
  SetaOfficesEstablished = 241,
  StaffDevelopment = 242,
  TracerStudies = 243,
  Trained = 244,
  TvetheicetPartnerships = 245,
  TvetPlacement = 246,
  OrganisationEmployer = 247,
  OrganisationProvider = 248,
  RoleSchema = 249,
  StandardIndustrialClassification = 250,
  Etqe = 251,
  School = 252,
  SchoolPhase = 253,
  SchoolSector = 254,
  SchoolStatus = 255,
}

export enum Object {
  SpBursaryFullBursaries = 147,
  SpECDFullUILayoutExample = 171,
  SpBursaryFullAccreditedInterventions = 172,
  SpBursaryWidgetBursariesByAgeBracket = 173,
  SpBursaryWidgetBursariesByEquityCode = 174,
  SpBursaryWidgetBursariesByFieldOfStudy = 175,
  SpBursaryWidgetBursariesByGender = 176,
  SpBursaryWidgetBursariesByStatus = 177,
  SpBursaryFullHEIEvidence = 183,
  SpBursaryFullHEIParticipation = 184,
  SpBursaryFullHEISubmissionsStats = 185,
  SpBursaryFullLearnersEvidence = 186,
  SpECDWidgetUILayoutExampleByAgeBracket = 187,
}

export enum ObjectType {
  Table = 1,
  Report = 2,
  Form = 3,
}

export enum OrganisationType {
  University = 1,
  TvetCollege = 2,
  CETCollege = 3,
  Smme = 4,
  NGO = 5,
  Startup = 6,
  Municipality = 7,
  SkillsDevelopmentProvider = 8,
  Seta = 9,
  Unknown = 10,
}

export enum PartOf {
  PartOfALearnership = 1,
  PartOfANonNQFIntervention = 2,
  PartOfAQualificationProgramme = 3,
  PartOfAnApprenticeship = 4,
  MiscellanousStandAlone = 5,
}

export enum PaymentFrequency {
  Monthly = 1,
  Quarterly = 2,
  Annually = 3,
  OnceOff = 4,
}

export enum Permission {
  Create = 1,
  Retrieve = 2,
  Update = 3,
  Delete = 4,
}

export enum PersonType {
  Entrepreneur = 1,
  Student = 2,
  Employee = 3,
  FinancialAidOfficer = 4,
  SigningOfficer = 5,
  BillingOfficer = 6,
  AccessOfficer = 7,
}

export enum POPIActStatus {
  Agree = 1,
  Disagree = 2,
  NA = 3,
}

export enum PortalOrigin {
  Internal = 1,
  External = 2,
}

export enum ProviderClass {
  Public = 1,
  Private = 2,
  Foreign = 3,
  InterimSaqaUseOnly = 4,
  MixedPublicAndPrivate = 5,
  NGOCBO = 6,
  Unknown = 7,
}

export enum ProviderStatus {
  Accredited = 1,
  Active = 2,
  Closed = 3,
  DeAccredited = 4,
  PreviouslyUsedInInterimProcess = 5,
  Proposed = 6,
  Provisional = 7,
  Reaccredited = 8,
  Registered = 9,
  Unsuccessful = 10,
  Withdrawn = 11,
}

export enum ProviderType {
  DevelopmentEnterpriseNGO = 1,
  Education = 2,
  EducationAndTraining = 3,
  Employer = 4,
  Training = 5,
}

export enum Province {
  EasternCape = 1,
  FreeState = 2,
  Gauteng = 3,
  KwazuluNatal = 4,
  Limpopo = 5,
  Mpumalanga = 6,
  NorthWest = 7,
  NorthernCape = 8,
  OutsideSouthAfrica = 9,
  SouthAfricaNational = 10,
  WesternCape = 11,
}

export enum QualificationLevel {
  NationalSeniorCertificate = 1,
  NationalDiploma = 2,
  BachelorsDegree = 3,
  HonoursDegree = 4,
  MastersDegree = 5,
  DoctoralDegree = 6,
}

export enum Quarter {
  Quarter1 = 1,
  Quarter2 = 2,
  Quarter3 = 3,
  Quarter4 = 4,
}

export enum RecommendationType {
  Recommended = 1,
  NotRecommended = 2,
  FutureFinancialYear = 3,
  AlreadyImplementing = 4,
}

export enum RejectionCategory {
  Eligibility = 1,
  Documentation = 2,
  Academic = 3,
  Administrative = 4,
  StrategicAlignment = 5,
  Financial = 6,
  Institutional = 7,
  Employment = 8,
}

export enum RejectionReason {
  DoesNotMeetAgeRequirements = 1,
  DoesNotMeetCitizenshipResidencyRequirements = 2,
  DoesNotMeetDisabilityRequirements = 3,
  DoesNotMeetGenderRequirements = 4,
  IncompleteApplication = 5,
  MissingOrInvalidIDDocument = 6,
  MissingAcademicRecordsTranscripts = 7,
  MissingProofOfResidence = 8,
  MissingBankingDetailsConfirmation = 9,
  SubmittedDocumentsNotValidCertified = 10,
  SubmittedDocumentsIllegibleUnclear = 11,
  DoesNotMeetAcademicRequirements = 12,
  NoProofOfAdmissionAcceptance = 13,
  QualificationNotApprovedForFunding = 14,
  PreviousAcademicFailurePoorPerformance = 15,
  ApplicationSubmittedAfterDeadline = 16,
  DuplicateApplication = 17,
  FalseOrMisleadingInformationProvided = 18,
  ApplicantDidNotRespondToQueries = 19,
  FieldOfStudyNotAlignedWithSetaPriorities = 20,
  NotInSetaSectorScope = 21,
  ProvincialRegionalQuotaReached = 22,
  EquityTargetsForCategoryReached = 23,
  BudgetAllocationExhausted = 24,
  AlreadyReceivingFundingFromAnotherSource = 25,
  MaximumFundingLimitYearsExceeded = 26,
  CourseCostExceedsProgrammeLimits = 27,
  TrainingInstitutionNotAccredited = 28,
  InstitutionNotOnApprovedProviderList = 29,
  InstitutionAccreditationSuspended = 30,
  DoesNotMeetEmploymentCriteria = 31,
  EmployerNotLevyPaying = 32,
  EmployerNotInGoodStanding = 33,
  MissingEmployerSupportConfirmation = 34,
  ProgrammeNotAvailableForUnemployedApplicants = 35,
}

export enum ReportingType {
  Quarterly = 1,
  Annually = 2,
}

export enum RiskRating {
  Red = 1,
  Amber = 2,
  Green = 3,
}

export enum Role {
  Administrator = 1,
  BursaryLearner = 2,
  Entrepreneur = 3,
  FinancialReports = 4,
  ManagementReports = 5,
  SetmisReports = 6,
  BursaryInstitutionOfficer = 7,
  BursaryManager = 8,
  BursaryEvaluator = 9,
  BursaryApprover = 10,
  PmvrManager = 11,
  PmvrPlanner = 12,
  SsetaAdmin = 13,
  FinancialAidOfficer = 14,
  SigningOfficer = 15,
  BillingOfficer = 16,
  Unassigned = 17,
  AccessOfficer = 18,
}

export enum RoleSchema {
  BursaryLearnerBursariesBursarylearner = 23,
  BursaryInstitutionOfficerBursariesPartnerB = 24,
  BursaryManagerBursariesPartnerB = 25,
  BursaryEvaluatorBursariesPartnerB = 26,
  BursaryApproverBursariesPartnerB = 27,
  PmvrManagerECDPartnerEcd = 28,
  PmvrPlannerPmvrManagementPmvr = 29,
  SsetaAdminPmvrManagementAdmin = 30,
  FinancialAidOfficerBursariesPartnerB = 31,
  SigningOfficerBursariesPartnerB = 32,
  SigningOfficerECDPartnerEcd = 33,
  SigningOfficerSPPartnerSp = 34,
  SigningOfficerSPIPartnerSpi = 35,
  BillingOfficerBursariesPartnerB = 36,
  BillingOfficerECDPartnerEcd = 37,
  BillingOfficerSPPartnerSp = 38,
  BillingOfficerSPIPartnerSpi = 39,
  AccessOfficerBursariesPartnerB = 41,
  AccessOfficerECDPartnerEcd = 42,
  AccessOfficerSPPartnerSp = 43,
  AccessOfficerSPIPartnerSpi = 44,
}

export enum SAQAField {
  AgricultureAndNatureConservation = 1,
  CultureAndArts = 2,
  BusinessCommerceAndManagementStudies = 3,
  CommunicationStudiesAndLanguage = 4,
  EducationTrainingAndDevelopment = 5,
  ManufacturingEngineeringAndTechnology = 6,
  HumanAndSocialStudies = 7,
  LawMilitaryScienceAndSecurity = 8,
  HealthSciencesAndSocialServices = 9,
  PhysicalMathematicalComputerAndLifeSciences = 10,
  Services = 11,
  PhysicalPlanningAndConstruction = 12,
}

export enum SAQALearningProgramme {
  DerivedGenericQualification = 1,
  LearningProgramme = 2,
  FullyGenericQualification = 3,
  NationalQualification = 4,
  InstitutionalGenericQualification = 5,
}

export enum SAQASubField {
  TransportOperationsAndLogistics = 1,
  SecondaryAgriculture = 2,
  EngineeringAndRelatedDesign = 3,
  SafetyInSociety = 4,
  ElectricalInfrastructureConstruction = 5,
  ManufacturingAndAssembly = 6,
  ProjectManagement = 7,
  EarthAndSpaceSciences = 8,
  HumanResources = 9,
  CulturalStudies = 10,
  PrimaryAgriculture = 11,
  CommunicationStudies = 12,
  IndustrialOrganizationalGovernanceAndHRDevelopment = 13,
  MediaStudies = 14,
  HospitalityTourismTravelGamingAndLeisure = 15,
  EarlyChildhoodDevelopment = 16,
  WholesaleAndRetail = 17,
  GeneralSocialScience = 18,
  OfficeAdministration = 19,
  Sport = 20,
  FinanceEconomicsAndAccounting = 21,
  EnvironmentalSciences = 22,
  PhysicalPlanningDesignAndManagement = 23,
  PublicAdministration = 24,
  PhysicalSciences = 25,
  PreventiveHealth = 26,
  InformationStudies = 27,
  AdultLearning = 28,
  LifeSciences = 29,
  DesignStudies = 30,
  PromotiveHealthAndDevelopmentalServices = 31,
  JusticeInSociety = 32,
  SovereigntyOfTheState = 33,
  PublicPolicyPoliticsAndDemocraticCitizenship = 34,
  NatureConservation = 35,
  Music = 36,
  Schooling = 37,
  CivilEngineeringConstruction = 38,
  Horticulture = 39,
  CurativeHealth = 40,
  VisualArts = 41,
  FabricationAndExtraction = 42,
  ForestryAndWoodTechnology = 43,
  PerformingArts = 44,
  Language = 45,
  Literature = 46,
  EnvironmentalRelations = 47,
  RuralAndAgrarianStudies = 48,
  InformationTechnologyAndComputerSciences = 49,
  CleaningDomesticHiringPropertyAndRescueServices = 50,
  PeopleHumanCentredDevelopment = 51,
  TraditionsHistoryAndLegacies = 52,
  ConsumerServices = 53,
  ReligiousAndEthicalFoundationsOfSociety = 54,
  BuildingConstruction = 55,
  Marketing = 56,
  Psychology = 57,
  PublicRelations = 58,
  FilmTelevisionAndVideo = 59,
  GenericManagement = 60,
  PersonalCare = 61,
  RehabilitativeHealthServices = 62,
  UrbanAndRegionalStudies = 63,
  Procurement = 64,
  HigherEducationAndTraining = 65,
  MathematicalSciences = 66,
}

export enum SchoolPhase {
  CombinedSchool = 1,
  SchoolOfSkills = 2,
  SpecialNeedsSchool = 3,
  SecondarySchool = 4,
  PrePrimarySchool = 5,
  HospitalSchool = 6,
  PrimarySchool = 7,
  YouthTrainingCentre = 8,
  IntermediateSchool = 9,
}

export enum SchoolSector {
  Public = 1,
  EarlyChildhoodDevelopmentCentre = 2,
  Independent = 3,
}

export enum SchoolStatus {
  PendingClose = 1,
  PendingOpen = 2,
  Open = 3,
}

export enum SETAType {
  AgriSetaAgricultureSectorEducationAndTrainingAuthorityPaetaAndSetasaMerged = 1,
  BanksetaBankingSectorEducationAndTrainingAuthority = 2,
  CathssetaCultureArtsTourismHospitalityAndSportsEducationAndTrainingAuthority = 3,
  CetaConstructionEducationAndTrainingAuthority = 4,
  ChietaChemicalIndustriesEducationAndTrainingAuthority = 5,
  EtdpSetaEducationTrainingAndDevelopmentPracticesSectorEducationAndTrainingAuthority = 6,
  EwsetaEnergySectorEducationAndTrainingAuthority = 7,
  FassetFinancialAndAccountingServicesSeta = 8,
  FoodbevFoodAndBeveragesManufacturingIndustrySectorEducationAndTrainingAuthority = 9,
  FPMSetaFibreProcessingManufacturingSectorEducationAndTrainingAuthority = 10,
  HWSetaHealthAndWelfareSectorEducationAndTrainingAuthority = 11,
  InsetaInsuranceSectorEducationAndTrainingAuthority = 12,
  LgsetaLocalGovernmentAndRelatedServicesSectorEducationAndTrainingAuthority = 13,
  MersetaManufacturingEngineeringAndRelatedServicesEducationAndTrainingAuthority = 14,
  MictsMediaInformationAndCommunicationTechnologiesSeta = 15,
  MQAMiningQualificationsAuthority = 16,
  PsetaPublicServiceSectorEducationAndTrainingAuthority = 17,
  SassetaSafetyAndSecuritySectorEducationAndTrainingAuthorityPoslecAndDidteta = 18,
  ServicesServicesSectorEducationAndTrainingAuthority = 19,
  TetaTransportEducationAndTrainingAuthority = 20,
  WRsetaWholesaleRetailSectorEducationAndTrainingAuthority = 21,
}

export enum SourceSystem {
  Lmis = 1,
  ELearning = 2,
  Pmis = 3,
}

export enum Stage {
  Feasibility = 1,
  Initial = 2,
}

export enum StageDependency {
  RootFeasibility = 1,
  FeasibilityInitial = 2,
}

export enum StatsSaArea {
  Albertskroon = 1,
  Albertville = 2,
}

export enum Status {
  Draft = 1,
  PendingApproval = 2,
  Approved = 3,
  Rejected = 4,
  Verified = 5,
  Signed = 6,
  Withdrawn = 7,
  Compliant = 8,
  NonCompliant = 9,
  Paid = 10,
  NotPaid = 11,
  Revoked = 12,
  Recommend = 13,
  NotRecommended = 14,
  FutureFinancialYear = 15,
  AlreadyImplementing = 16,
  Completed = 17,
  PendingSignature = 18,
  NotSigned = 19,
  Achievable = 20,
  NotAchievable = 21,
  NotStarted = 22,
  InProgress = 23,
  Delayed = 24,
  Skipped = 25,
  Expired = 26,
  Open = 27,
  Resolved = 28,
  InitiatedCommunication = 29,
  CompletedCommunication = 30,
  Failed = 31,
  NominationSubmitted = 33,
  NominationApproved = 34,
  NominationRejected = 35,
  ApplicationSubmitted = 36,
  ApplicationApproved = 37,
  ApplicationRejected = 38,
  ApplicationCompleted = 39,
  Requested = 40,
  Submitted = 41,
  Processed = 42,
  Invoiced = 43,
  Active = 44,
  Cancelled = 45,
  PaymentBatched = 46,
  PaymentSubmitted = 47,
  PaymentAuthorised = 48,
  PaymentCompleted = 49,
}

export enum StatusCascadeRule {
  PerformancePlanProgrammeDraft = 1,
  PerformancePlanProgrammeInProgress = 2,
  PerformancePlanProgrammePendingApproval = 3,
  PerformancePlanProgrammeCompleted = 4,
  PerformancePlanSubProgrammeDraft = 5,
  PerformancePlanSubProgrammeInProgress = 6,
  PerformancePlanSubProgrammePendingApproval = 7,
  PerformancePlanSubProgrammeCompleted = 8,
  PerformancePlanIndicatorDraft = 9,
  PerformancePlanIndicatorInProgress = 10,
  PerformancePlanIndicatorPendingApproval = 11,
  PerformancePlanIndicatorCompleted = 12,
}

export enum StatusObject {
  IndicatorDraft = 1,
  ProgrammeDraft = 2,
  InterventionDraft = 3,
  SubProgrammeDraft = 4,
  IndicatorIssueOpen = 5,
  IndicatorIssueResolved = 6,
  IndicatorIssueExpired = 7,
  ApplicationNonCompliant = 8,
  ApplicationCompliant = 11,
  DisbursementNotPaid = 12,
  DisbursementPaid = 13,
  DisbursementRevoked = 14,
  StageInstanceNotStarted = 15,
  StageInstanceInProgress = 16,
  StageInstanceDelayed = 17,
  StageInstanceSkipped = 18,
  StageInstanceCompleted = 19,
  OrganisationContractDraft = 20,
  OrganisationContractPendingSignature = 21,
  OrganisationContractFailed = 22,
  OrganisationContractCompleted = 24,
  OrganisationContractInProgress = 33,
  OrganisationDraft = 34,
  OrganisationApproved = 35,
  DocumentSignaturePendingSignature = 36,
  DocumentSignatureSigned = 37,
  PerformancePlanDraft = 38,
  PerformancePlanInProgress = 39,
  PerformancePlanPendingApproval = 40,
  PerformancePlanCompleted = 41,
  BursaryApplicantNominationSubmitted = 48,
  BursaryApplicantNominationApproved = 49,
  BursaryApplicantNominationRejected = 50,
  BursaryApplicantApplicationSubmitted = 51,
  BursaryApplicantApplicationApproved = 52,
  BursaryApplicantApplicationRejected = 53,
  BursaryApplicantApplicationCompleted = 54,
  OrganisationPendingSignature = 55,
  OrganisationInProgress = 56,
  OrganisationFailed = 57,
  BursaryApplicantApplicationContractInProgress = 59,
  BursaryApplicantApplicationPendingSignature = 60,
  BursaryApplicantApplicationFailed = 61,
  BursaryApplicantDraft = 62,
  BursaryApplicantRejectionReasonDraft = 63,
  BursaryApplicantRejectionReasonWithdrawn = 64,
  OrganisationInvoiceDraft = 65,
  OrganisationInvoiceRequested = 66,
  OrganisationInvoiceSubmitted = 67,
  OrganisationInvoicePaid = 68,
  OrganisationInvoiceRejected = 70,
  OrganisationInvoiceProcessed = 71,
  OrganisationInvoiceInvoiced = 72,
  BursaryApplicantAppealActive = 73,
  BursaryApplicantAppealResolved = 74,
  BursaryApplicantAppealCancelled = 75,
  BursaryApplicantPaymentBatched = 76,
  BursaryApplicantPaymentSubmitted = 77,
  BursaryApplicantPaymentAuthorised = 78,
  BursaryApplicantPaymentCompleted = 79,
  PartnerRoleRequestDraft = 80,
  PartnerRoleRequestPendingApproval = 81,
  PartnerRoleRequestApproved = 82,
  PartnerRoleRequestRejected = 83,
  PartnerRoleRequestCompleted = 84,
  StaffRoleRequestDraft = 87,
  StaffRoleRequestPendingApproval = 88,
  StaffRoleRequestApproved = 89,
  StaffRoleRequestRejected = 90,
  StaffRoleRequestCompleted = 91,
}

export enum StatusObjectPermission {
  PerformancePlanDraftCreate = 1,
  PerformancePlanDraftRetrieve = 2,
  PerformancePlanDraftUpdate = 3,
  PerformancePlanDraftDelete = 4,
  PerformancePlanInProgressCreate = 5,
  PerformancePlanInProgressRetrieve = 6,
  PerformancePlanInProgressUpdate = 7,
  PerformancePlanInProgressDelete = 8,
  PerformancePlanPendingApprovalCreate = 9,
  PerformancePlanPendingApprovalRetrieve = 10,
  PerformancePlanPendingApprovalUpdate = 11,
  PerformancePlanPendingApprovalDelete = 12,
  PerformancePlanCompletedCreate = 13,
  PerformancePlanCompletedRetrieve = 14,
  PerformancePlanCompletedUpdate = 15,
  PerformancePlanCompletedDelete = 16,
}

export enum SupportType {
  Bursary = 1,
  Construction = 2,
  Equipment = 3,
  PivotalSkillsTraining = 4,
  NonPivotalSkillsTraining = 5,
  CapacitationWorkshop = 6,
  ELearning = 7,
}

export enum SystemUserType {
  System = -1,
  Learner = 1,
  External = 2,
  Staff = 3,
}

export enum Template {
  EmailResetPassword = 1,
  EmailLoginMFA = 2,
  BursaryParticipationInvite = 5,
  InstitutionSigningInvite = 9,
  BursaryApplicantApprovalInvite = 10,
  InvitationToRegister = 12,
  OrganisationContractSignatureRequired = 13,
  OrganisationInvitationToParticipate = 14,
  BursaryApplicantNominationToApplyForABursary = 15,
  BursaryApplicantBursaryApplicationUnsuccessful = 16,
  BursaryApplicantBursaryContractSignatureRequired = 17,
}

export enum Template {
  SMSResetPassword = 3,
  SMSLoginMFA = 4,
}

export enum Template {
  InstitutionContract = 7,
  BursaryContract = 8,
}

export enum TemplateType {
  Email = 1,
  SMS = 2,
  Notification = 3,
  Document = 4,
}

export enum Title {
  Mr = 1,
  Mrs = 2,
  Ms = 3,
  Dr = 4,
  Prof = 5,
}

export enum TradeTestResult {
  Competent = 1,
  NotYetCompetent = 2,
}

export enum TradeTestResultReason {
  TBA = 1,
}

export enum YearOfStudy {
  FirstYear = 1,
  SecondYear = 2,
  ThirdYear = 3,
  FourthYear = 4,
  FifthYear = 5,
  SixthYear = 6,
  SeventhYear = 7,
  EighthYear = 8,
  NinethYear = 9,
  TenthYear = 10,
}